plugin: azure_rm
include_vm_resource_groups:
  - b2c6c
auth_source: auto
conditional_groups:
  development: "'development' in tags.environment | default('none')"
  production: "'production' in tags.environment | default('none')"
  vault: "'vault' in tags.environment | default('none')"
  prometheus: "'prometheus' in tags.environment | default('none')"