- name: Configure Production VMs
  hosts: production
  become: yes
  tasks:
    - name: Ensure Docker is running
      service:
        name: docker
        state: started

    - name: Create Compose file
      copy:
        content: |
          # docker-compose.yml
          name: ansible-compose-stack
          services:
            frontend:
              image: snailcape/cipipelinetest
              restart: always
              ports:
                - 80:5000
            backend:
              image: ichishihoness/my-backend:latest
              restart: always
              ports: 
                - 8000:8000
              links:
                - db
              environment:
                DB_USER: "{{ DB_USER }}"
                DB_PASSWORD: "{{ DB_PASSWORD }}"
                DB_HOST: db
                DB_NAME: "{{ DB_NAME }}"

            db:
              image: mariadb:latest
              restart: always
              environment:
                MYSQL_ROOT_PASSWORD: "{{ DB_PASSWORD }}"
              volumes:
                - db_data:/var/lib/mysql
              ports:
                - 3306:3306

            backup:
              image: fradelg/mysql-cron-backup
              restart: always
              environment:
                MYSQL_HOST: db
                MYSQL_PORT: 3306
                MYSQL_USER: root
                MYSQL_PASS: "{{ DB_PASSWORD }}"
                CRON_TIME: "0 3 * * *"  # Daily at 3am
                BACKUP_DIR: /backups
              volumes:
                - db_backup:/backups

            watchtower:
              image: containrrr/watchtower
              restart: always
              volumes:
                - /var/run/docker.sock:/var/run/docker.sock
              command: --cleanup --interval 300

          volumes:
            db_data:
        dest: /tmp/dockercompose-file

    - name: Launch Docker Compose
      ansible.builtin.command: docker compose -f /tmp/dockercompose-file up --detach

    - name: Update Dynamic DNS Record
      shell: curl $DDNS_LINK