- name: Configure VMs
  hosts: all
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Test Docker
      ansible.builtin.command: docker run hello-world