- name: Create Azure Storage Account and Blob Container
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars/main.yml
  collections:
    - azure.azcollection
  tasks:
    - name: Create Storage account
      azure_rm_storageaccount:
        resource_group: "{{ resource_group_name }}"
        name: "{{ storage_account_name }}"
        account_type: Standard_LRS
        kind: StorageV2
        enable_https_traffic_only: yes
      vars:
        storage_account_name: "MainAzureStorageAccount"

    - name: Create blob container
      azure_rm_storageblob:
        resource_group: "{{ resource_group_name }}"
        storage_account_name: "{{ storage_account_name }}"
        name: "{{ blob_container_name }}"
        public_access: container
      vars:
        blob_container_name: "openscap-reports"