- name: Create Azure Storage Account and Blob Container
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars/main.yml
  vars:
    storage_account_name: "b2c6storageacct"
    blob_container_name: "openscap-reports"
  collections:
    - azure.azcollection
  tasks:
    - name: Check if Storage account exists
      azure_rm_storageaccount_info:
        resource_group: "{{ resource_group_name }}"
        name: "{{ storage_account_name }}"
      register: storage_account_info
      ignore_errors: yes

    - name: Create Storage account if it does not exist
      azure_rm_storageaccount:
        resource_group: "{{ resource_group_name }}"
        name: "{{ storage_account_name }}"
        account_type: Standard_LRS
        kind: StorageV2
        https_only: yes
      when: storage_account_info is failed

    - name: Check if Blob container exists using Azure CLI
      command: >
        az storage container show --account-name "{{ storage_account_name }}" --name "{{ blob_container_name }}"
      register: blob_container_check
      ignore_errors: yes

    - name: Create Blob container if it does not exist
      azure_rm_storageblob:
        resource_group: "{{ resource_group_name }}"
        storage_account_name: "{{ storage_account_name }}"
        container_name: "{{ blob_container_name }}"
      when: blob_container_check is failed
