---
- name: Install Serverspec and required packages
  hosts: all
  become: yes
  tasks:
    - name: Update apt repository cache
      apt:
        update_cache: yes

    - name: Install Ruby and required packages
      apt:
        name:
          - ruby-full
          - build-essential
          - libssl-dev
        state: present

    - name: Install Bundler
      gem:
        name: bundler
        state: present
        user_install: no

    - name: Create Gemfile for Serverspec
      copy:
        dest: /home/ubuntu/Gemfile
        content: |
          source 'https://rubygems.org'
          gem 'serverspec'
          gem 'docker-api'
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Install gems from Gemfile
      command: bundle install
      args:
        chdir: /home/ubuntu

    - name: Create Serverspec test file
      copy:
        dest: /home/ubuntu/spec/docker_container_spec.rb
        content: |
          require 'serverspec'
          require 'docker-api'

          # Use Docker backend
          set :backend, :docker
          set :docker_container, 'ansible-compose-stack-frontend'  # docker container name 

          # Check if docker container runs
          describe docker_container('ansible-compose-stack-frontend') do
            it { should be_running }
          end

          # Check if right port is opened (e.g. 443 for HTTPS)
          describe port(443) do
            it { should be_listening }
          end

          # Check if frontend-website gives right response
          describe command('curl http://developmentvm1-klasb2c.westeurope.cloudapp.azure.com/login') do
            its(:stdout) { should match /Inloggen/ }  # suitable text from the website
            its(:exit_status) { should eq 0 }
          end
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Run Serverspec tests
      command: bundle exec rspec spec/docker_container_spec.rb
      args:
        chdir: /home/ubuntu
