name: Run Ansible playbooks

on:
  workflow_dispatch:
    inputs:
      numberOfDevelopmentVms:
        description: "Number of testing environment VMs to create"
        required: true
        default: 1
        type: number
      numberOfProductionVms:
        description: "Number of production environment VMs to create"
        required: true
        default: 1
        type: number

jobs:
  Restore_VMs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Ansible
        run: |
          pip install ansible
          ansible-galaxy collection install azure.azcollection --force

      - name: Install Azure Collection requirements
        run: pip install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements.txt

      - name: Make SSH and logs directory
        run: |
          mkdir -p ~/.ssh
          mkdir -p ~/logs

      - name: Login to Azure
        run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Make shared resources
        working-directory: ./playbooks
        run: ansible-playbook creation/setup.yml

      - name: Create VMs
        working-directory: ./playbooks
        run: |
          (ansible-playbook creation/vault.yml > ~/logs/vault-create.log 2>&1) &
          (ansible-playbook creation/development.yml -e DEVELOPMENT_VMS=${{ github.event.inputs.numberOfDevelopmentVms }} > ~/logs/development-create.log 2>&1) &
          (ansible-playbook creation/production.yml -e PRODUCTION_VMS=${{ github.event.inputs.numberOfProductionVms }} > ~/logs/production-create.log 2>&1) &

          wait

      - name: Configure VMs
        working-directory: ./playbooks
        env:
          DOCKER_DB_USER: ${{ secrets.DOCKER_DB_USER }}
          DOCKER_DB_PASSWORD: ${{ secrets.DOCKER_DB_PASSWORD }}
          DOCKER_DB_NAME: ${{ secrets.DOCKER_DB_NAME }}
          VAULT_USER: ${{ secrets.VAULT_USER }}
          VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD }}
          VAULT_DDNS_LINK: ${{ secrets.VAULT_DDNS_LINK }}
          PRODUCTION_DDNS_LINK: ${{ secrets.PRODUCTION_DDNS_LINK }}
          VAULT_DB_USERNAME: ${{ secrets.VAULT_DB_USERNAME }}
          VAULT_DB_PASSWORD: ${{ secrets.VAULT_DB_PASSWORD }}
        run: |
          (ansible-playbook configuration/vault.yml -e VAULT_USER="$VAULT_USER" -e VAULT_PASSWORD="$VAULT_PASSWORD" -e VAULT_DB_USERNAME="$VAULT_DB_USERNAME" -e VAULT_DB_PASSWORD="$VAULT_DB_PASSWORD" -e DDNS_LINK="$VAULT_DDNS_LINK" > ~/logs/vault-configure.log 2>&1) &

          (ansible-playbook configuration/development.yml -e DB_USER="$DOCKER_DB_USER" -e DB_PASSWORD="$DOCKER_DB_PASSWORD" -e DB_NAME="$DOCKER_DB_NAME" > ~/logs/development-configure.log 2>&1) &
          (ansible-playbook configuration/production.yml -e DB_USER="$DOCKER_DB_USER" -e DB_PASSWORD="$DOCKER_DB_PASSWORD" -e DB_NAME="$DOCKER_DB_NAME" -e DDNS_LINK="$PRODUCTION_DDNS_LINK" > ~/logs/production-configure.log 2>&1) &

          wait
      
      - name: Log out of Azure
        if: always()
        run: az logout

      - name: Export secrets to Vault
        continue-on-error: true
        env:
          VAULT_USER: ${{ secrets.VAULT_USER }}
          VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD }}
          VAULT_URL: ${{ secrets.VAULT_URL }}
          VAULT_SECRET_PATH: ${{ secrets.VAULT_SECRET_PATH }}
          VAULT_DB_SECRET_PATH: ${{ secrets.VAULT_DB_SECRET_PATH }}
          DOCKER_DB_USER: ${{ secrets.DOCKER_DB_USER }}
          DOCKER_DB_PASSWORD: ${{ secrets.DOCKER_DB_PASSWORD }}
        run: |
          sudo apt-get install -y jq curl
          clientToken=$(curl -X POST "$VAULT_URL/v1/auth/userpass/login/$VAULT_USER" -H "Content-Type: application/json" -d "{\"password\" :  \"$VAULT_PASSWORD\" }" | jq -r ".auth.client_token")
          ssh_key_content=$(cat ~/.ssh/ansible_key.pem | jq -Rs .)
          curl -X POST "$VAULT_URL/v1/$VAULT_SECRET_PATH" -H "X-Vault-Token: $clientToken" -d "{\"key\": $ssh_key_content}"
          user=vault
          host=vault-klasb2c.westeurope.cloudapp.azure.com
          ssh -i ~/.ssh/ansible_key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $user@$host "sudo apt-get install jq -y && sudo cat ~/vault_keys.json | jq -r '.root_token' > ~/vault_token"
          clientToken=$(ssh -i sshKey.txt -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $user@$host "sudo cat ~/vault_token")
          curl -X POST "$VAULT_URL/v1/$VAULT_DB_SECRET_PATH" -H "X-Vault-Token: $clientToken" -d "{\"username\": \"$DOCKER_DB_USER\", \"password\": \"$DOCKER_DB_PASSWORD\"}"

        # Retrieve SSH key from Vault like so:
        # clientToken=$(curl -X POST "$VAULT_URL/v1/auth/userpass/login/$VAULT_USER" -H "Content-Type: application/json" -d "{\"password\" :  \"$VAULT_PASSWORD\" }" | jq -r ".auth.client_token")
        # curl -X GET "$VAULT_URL/v1/$VAULT_SECRET_PATH" -H "X-Vault-Token: $clientToken" | jq -r '.data."key"'

      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: logs-${{ github.run_id }}
          path: |
            ~/logs/

      - name: Shoutout
        if: always()
        run: |
          echo " "
          echo -e "\e[34m              ___    ___             \e[0m"
          echo -e "\e[34m  _         / __)  / __)            \e[0m"
          echo -e "\e[34m_| |_ ___ _| |__ _| |__ _____ _____ \e[0m"
          echo -e "\e[34m(_   _) _ (_   __|_   __) ___ | ___ |\e[0m"
          echo -e "\e[34m  | || |_| || |    | |  | ____| ____|\e[0m"
          echo -e "\e[34m   \__)___/ |_|    |_|  |_____)_____)\e[0m"

  run-serverspec-tests:
    runs-on: ubuntu-latest
    needs: Restore_VMs
    steps:
      - uses: actions/checkout@v4

      - name: Install Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0' 

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run Serverspec tests
        run: |
          bundle exec rspec spec/
        continue-on-error: true
        id: serverspec

  notify-on-failure:
    runs-on: ubuntu-latest
    needs: run-serverspec-tests
    if: failure()
    steps:
      - uses: actions/checkout@v4

      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: |
            :x: Serverspec tests failed for ${{ github.repository }} on branch ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            Actor: ${{ github.actor }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
