name: Run playbooks

# Controls when the workflow will run
on:
  workflow_dispatch:
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Install Ansible
        run: |
          pip install ansible
          ansible-galaxy collection install azure.azcollection --force
      - name: print files
        run: |
          sudo apt-get install tree
          tree /home/runner/.ansible/collections/ansible_collections/azure/azcollection
      - name: Install Azure Collection requirements
        run: pip install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements.txt
      - name: Run Ansible playbook
        run: ansible-playbook playbooks/test.yml        

