name: Run Ansible playbooks

on:
  workflow_dispatch:

jobs:
  Create_VMs:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Ansible
        run: |
          pip install ansible
          ansible-galaxy collection install azure.azcollection --force

      - name: Install Azure Collection requirements
        run: pip install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements.txt

      - name: Configure Azure credentials
        run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Make SSH directory
        run: mkdir /home/runner/.ssh

      - name: Make VMs
        working-directory: ./playbooks
        run: ansible-playbook create_vms.yml

      # - name: Export SSH key
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: privatekey.pem
      #     path: "~/.ssh/ansible_key.pem"
      #     retention-days: 1

      - name: Configure VMs
        working-directory: ./playbooks
        env:
          DOCKER_DB_USER: ${{ secrets.DOCKER_DB_USER }}
          DOCKER_DB_PASSWORD: ${{ secrets.DOCKER_DB_PASSWORD }}
          DOCKER_DB_NAME: ${{ secrets.DOCKER_DB_NAME }}
        run: ansible-playbook configure_vms.yml -e DB_USER="$DOCKER_DB_USER" -e DB_PASSWORD="$DOCKER_DB_PASSWORD" -e DB_NAME="$DOCKER_DB_NAME"
