name: Run Ansible playbooks

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  Create_VMs:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Ansible
        run: |
          pip install ansible
          ansible-galaxy collection install azure.azcollection --force

      - name: print files
        run: |
          sudo apt-get install tree
          tree /home/runner/.ansible/collections/ansible_collections/azure/azcollection

      - name: Install Azure Collection requirements
        run: pip install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements.txt

      - name: Configure Azure credentials
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Maak VMs
        run: |
          cd playbooks/
          ansible-playbook create_vms.yml

